vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        terrain_images:
            uri_prefix: /uploads/terrains
            upload_destination: '%kernel.project_dir%/public/uploads/terrains'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
